<?php
/**
 * AverageRatingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\RatingService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
<<<<<<< HEAD
 * Rating API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
=======
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
>>>>>>> 853c97ce884be8eae2441959755e3e9e3b1b996a
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VentureLeap\RatingService;

/**
 * AverageRatingTest Class Doc Comment
 *
 * @category    Class
 * @description AverageRating
 * @package     VentureLeap\RatingService
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AverageRatingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AverageRating"
     */
    public function testAverageRating()
    {
    }

    /**
     * Test attribute "product_uuid"
     */
    public function testPropertyProductUuid()
    {
    }

    /**
     * Test attribute "average_ratings"
     */
    public function testPropertyAverageRatings()
    {
    }
}
