<?php
/**
 * RatingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\RatingService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rating API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\RatingService;

use VentureLeap\RatingService\Configuration;
use VentureLeap\RatingService\ApiException;
use VentureLeap\RatingService\ObjectSerializer;

/**
 * RatingApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\RatingService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RatingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteRatingItem
     *
     * Removes the Rating resource..
     *
     */
    public function testDeleteRatingItem()
    {
    }

    /**
     * Test case for findAverageRatingRatingItem
     *
     * Retrieves a Rating resource..
     *
     */
    public function testFindAverageRatingRatingItem()
    {
    }

    /**
     * Test case for getRatingCollection
     *
     * Retrieves the collection of Rating resources..
     *
     */
    public function testGetRatingCollection()
    {
    }

    /**
     * Test case for getRatingItem
     *
     * Retrieves a Rating resource..
     *
     */
    public function testGetRatingItem()
    {
    }

    /**
     * Test case for postRatingCollection
     *
     * Creates a Rating resource..
     *
     */
    public function testPostRatingCollection()
    {
    }

    /**
     * Test case for putRatingItem
     *
     * Replaces the Rating resource..
     *
     */
    public function testPutRatingItem()
    {
    }
}
